### ISSUE TITLE
Tracking issues of opendalfs 0.1 release

### ISSUE THREAD

**Issue by Xuanwo** [fsspec/opendalfs#6]
This issue is used to track the progress of opendalfs 0.1 release. Welcome to join in the developmenet by leaving your comments here.

- In 0.1 release, we might not cover all supported service. We will provide `memory`, `fs`, `s3`, `azblob`, `gcs`, `oss` at least.
- In 0.1 release, we will only have blocking API first. Async API is on our plan.

## Tasks

- [x] Figure out all fsspec APIs that need to implement (maybe refer to s3fs and ossfs)
- [ ] Implement OpendalFileSystem APIs
  - [ ] fsid
  - [ ] mkdir
  - [ ] mkdirs
  - [ ] rmdir
  - [ ] ls
  - [ ] info
  - [ ] rm_file
  - [ ] _open
  - [ ] created
  - [ ] modified
- [ ] Implement OpendalBufferedFile APIs
  - [ ] _upload_chunk
  - [ ] _initiate_upload
  - [ ] _fetch_range
- [x] Figure out how to perform releases
  - I expect to have a package for every different service.
- [ ] Figure out how to do test on different service
- [ ] Add docs for service.

**Comment by Xuanwo** [comment]
cc @wey-gu and @BeautyyuYanli, are there any features you'd like included in our initial release?

**Comment by BeautyyuYanli** [comment]
I think no need to have a package for every different service, since the opendal has all in one package

**Comment by BeautyyuYanli** [comment]
Some methods have already been implemented in the abstract class. Others we can implement them by opendal-python or directly rust binding. Maybe the package will not depend on opendal-python, but becomes a new Python binding.

**Comment by Xuanwo** [comment]
> I think no need to have a package for every different service, since the opendal has all in one package

Hi, thanks for joining the discussion first.

Please allow me to provide some context before going deeper:

- the opendal rust core have all services in a single crate (the package in Rust). Users can enable only the services they need, rather than importing unnecessary ones.
- The python binding for OpenDAL has opted to include as many services as possible. However, this decision has not been well-received by the community because it results in a very large python package. Users are required to install the entire huge package even if they only need access to S3.
  ![image](https://github.com/user-attachments/assets/ee966834-d189-4d3e-935d-ce7ac3ff0bc7)
- To further complicate matters, some services require additional dynamic libraries to function. For instance, `sqlite` requires `libsqlite`, while `hdfs` needs both `libhdfs` and `libjvm`. We must decide whether to discontinue support for these services or require all users to install the necessary libraries.

In `opendalfs`, I plan to separate various services into distinct packages, allowing users to selectively install the services they need, such as with `pip install opendalfs[s3, azblob]`. The implementation details are still being researched; however, I personally believe this is the better approach.

> Maybe the package will not depend on opendal-python, but becomes a new Python binding.

I believe we can directly build from opendal rust to better align with fsspec's behavior without additional abstraction.

**Comment by Xuanwo** [comment]
I have establish the project layout. Adding a service should be as easy as add a simple config: https://github.com/fsspec/opendalfs/pull/11

**Comment by Xuanwo** [comment]
@BeautyyuYanli, I have updated the API that we need to implement and added place holders for them, welcome to take a look.

**Comment by martindurant** [comment]
I would like to add to your list:
- decide on async or blocking API (this might already be done)
- pick a protocol string, and think about how users should express the inner protocol. For example, "opendal://gdrive/shared_folder/path/file" might be a reasonable way to refer to a path which is to be handled by DAL, but resides in gdrive (or s3, or ...). Or you could introduce separate protocols for each, like "dal_gdrive", or you might want to "register" your implementation to overwrite the known protocols in fsspec, such that "gdrive" refers to DAL's implementation for the rest of the session.

**Comment by dongshunyao** [comment]
Hello! I would like to contribute to this project.

I have experience with Python and C++, but I am not yet familiar with Rust. I am very willing to learn it for this project.

I am still a beginner in open source. @Xuanwo Could you please assign me some simple and basic tasks to familiarize me with the whole process? I could get started and learn from them.

Thanks to @wey-gu for the guidance!

**Comment by Xuanwo** [comment]
> Hello! I would like to contribute to this project.
> 
> I have experience with Python and C++, but I am not yet familiar with Rust. I am very willing to learn it for this project.
> 
> I am still a beginner in open source. @Xuanwo Could you please assign me some simple and basic tasks to familiarize me with the whole process? I could get started and learn from them.
> 
> Thanks to @wey-gu for the guidance!

Hi, @dongshunyao, nice to meet you! I think we can start with implementing `info` or `mkdir` like we do for `ls`.

**Comment by dongshunyao** [comment]
> > Hello! I would like to contribute to this project.
> > I have experience with Python and C++, but I am not yet familiar with Rust. I am very willing to learn it for this project.
> > I am still a beginner in open source. @Xuanwo Could you please assign me some simple and basic tasks to familiarize me with the whole process? I could get started and learn from them.
> > Thanks to @wey-gu for the guidance!
> 
> Hi, @dongshunyao, nice to meet you! I think we can start with implementing `info` or `mkdir` like we do for `ls`.

Thank you! I prefer to implement `mkdir` first. Should I write it in Rust like [fs.rs#L18](https://github.com/fsspec/opendalfs/blob/main/crates/core/src/fs.rs#L18) and in Python like [fs.py#L39](https://github.com/fsspec/opendalfs/blob/main/opendalfs/fs.py#L39), and complete the corresponding tests?

**Comment by Xuanwo** [comment]
> Thank you! I prefer to implement `mkdir` first. Should I write it in Rust like [fs.rs#L18](https://github.com/fsspec/opendalfs/blob/main/crates/core/src/fs.rs?rgh-link-date=2024-09-24T16%3A45%3A21Z#L18) and in Python like [fs.py#L39](https://github.com/fsspec/opendalfs/blob/main/opendalfs/fs.py?rgh-link-date=2024-09-24T16%3A45%3A21Z#L39), and complete the corresponding tests?

Exactly!

**Comment by dongshunyao** [comment]
> > Thank you! I prefer to implement `mkdir` first. Should I write it in Rust like [fs.rs#L18](https://github.com/fsspec/opendalfs/blob/main/crates/core/src/fs.rs?rgh-link-date=2024-09-24T16%3A45%3A21Z#L18) and in Python like [fs.py#L39](https://github.com/fsspec/opendalfs/blob/main/opendalfs/fs.py?rgh-link-date=2024-09-24T16%3A45%3A21Z#L39), and complete the corresponding tests?
> 
> Exactly!

Hi! I am so sorry for the delay in this PR https://github.com/fsspec/opendalfs/pull/18, which was caused by my health reasons and some unexpected situations. I implemented the `info` because this PR https://github.com/fsspec/opendalfs/pull/17 implemented the `mkdir`. Please feel free to look it over and comment. Thank you!

**Comment by wey-gu** [comment]
> I would like to add to your list:
> 
> - decide on async or blocking API (this might already be done)
> 

We impl both async and blocking APIs following the method name convention rules of fsspec.s3fs as a protocol: async methods starts with _, also the blocking API leverages the fsspec asyn sync wrappers. Underlying we wire the pyo3 bridged rust future async methods to _foo methods.

In recent PR #19 :) what do you think?

cc @Xuanwo

**Comment by wey-gu** [comment]
#20 made the ci work.

**Comment by Xuanwo** [comment]
Repurpose this target according to https://github.com/fsspec/opendalfs/issues/24.

**Comment by PsiACE** [comment]
Most of the interfaces here have already been implemented, except for `fsid` and `created`. I checked `s3fs`, and I think it generally follows the same conventions.

I think we should release a version and gather some feedback.
